export const subfolderIconMap: Record<string, string> = {
  biomes: "worldgen_file",
  blocks: "blocks_file",
  dialogue: "chat_type_file",
  entities: "entities_file",
  features: "features_file",
  feature_rules: "features_file",
  item_catalog: "item_modifier_file",
  items: "items_file",
  loot_tables: "loot_table_file",
  recipes: "recipe_file",
  spawn_rules: "spawn_rules_file",
  trading: "trading_file",
  worldgen: "worldgen_file",

  atmospherics: "fogs_file",
  attachables: "attachables_file",
  block_culling: "block_culling_file",
  color_grading: "shaders_file",
  entity: "entities_file",
  fogs: "fogs_file",
  font: "font_file",
  models: "models_file",
  particles: "particles_file",
  render_controllers: "render_controllers_file",
  ui: "ui_file",
}
